spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./data/download_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

command:
  line:
    runner:
      enabled: true